services:
  usersdatapostgres:
    container_name: usersdatapostgres
    image: postgis/postgis:16-3.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: rajeshhamal
      POSTGRES_PASSWORD: nepatopsabthikthak
      POSTGRES_DB: mapsdatabase
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    volumes:
      - usersdata:/var/lib/postgresql/data
    networks:
      - mapsnetwork

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:5.3.2
    restart: unless-stopped
    environment:
      PBF_URL: https://download.geofabrik.de/asia/nepal-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/nepal-updates/
      NOMINATIM_PASSWORD: password123
    ports:
      - 8080:8080
    volumes:
      - nomatimdata:/var/lib/postgresql/14/main
    depends_on:
      - usersdatapostgres
    networks:
      - mapsnetwork

  adminer:
    container_name: adminer
    image: adminer:5
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: usersdatapostgres
    ports:
      - 8090:8080
    networks:
      - mapsnetwork
    depends_on:
      - usersdatapostgres

networks:
  mapsnetwork:

volumes:
  usersdata:
  nomatimdata:
