import db from "./src/db/index";
import { address } from "./src/models/address";
import { property } from "./src/models/property";

const validUuidForAddress = [
  "22089603-4b41-4b17-9b53-7c6dc11552aa",
  "08df6b47-cf13-424e-8e90-3c19b53c3c27",
  "90b34fd2-0aee-43d2-b21d-947df386e6cc",
  "30910bb1-7919-4b36-aede-aa8720d4401c",
  "abed05cd-7dbb-4ed6-a114-0979818b5950",
  "1458a26b-8fa4-4135-bcc5-f39142a3c847",
  "e5a96186-6701-4b73-8359-5b5a59075b94",
  "4252b11b-a192-40f3-b875-57bc760969cd",
  "a9bf42b6-ae24-4b82-9803-1ea5bf3ae992",
  "88928dea-cc68-4c7d-b621-188e2ce801a6",
  "881e2242-71eb-4a61-ad64-2982ab713d1c",
  "23ce6fcf-e0bc-46f0-873a-54577d118d45",
  "30d29ac1-0eff-43d4-8c0b-c6e3c1499a6c",
  "1c22da1a-5763-4cd8-b018-f840a1b1b405",
  "3e0cc7fd-9a05-4b76-abf3-ab89e4cfa1f1",
];

const validUuidForProperty = [
  "07175f5a-f264-4aaf-b2d4-111c7108716b",
  "0717fc4d-9819-4b74-87b8-cfe7233011ca",
  "080ece73-b73d-4068-aad6-66a8f74dc3b2",
  "097c5e42-9b5c-4f86-bace-f943f194a1ef",
  "0b650fa3-0463-4042-96c9-f01015b5efa7",
  "0c344de6-fc6f-4244-9137-062e0dcbc8e1",
  "0d150bcc-0e97-49f3-bbba-4fa9ff1cee97",
  "1029aaf2-fdb0-4040-9771-a2acbc7c8a2d",
  "10e5e928-936d-4bfb-9cf8-433a9a5b2b88",
  "144ca929-4d66-4aeb-8b93-6a9c60966dd2",
  "166b620e-1da7-4851-929a-05ae34ed578a",
  "184232b3-c023-49ea-9b3b-a08d6bec298a",
  "1b54f00f-e36f-4684-a270-432165f68892",
  "1c22027a-0bc7-4523-a9e4-1bfa22792c6d",
  "2246c658-4993-43ce-ad9a-b8e9f110d972",
];

const addresses = [
  {
    id: validUuidForAddress[0],
    houseNumber: "12",
    street: "Durbar Marg",
    wardNumber: 1,
    municipality: "Kathmandu Metropolitan City",
    city: "Kathmandu",
    district: "Kathmandu",
    province: "Bagmati",
    latitude: 27.7105,
    longitude: 85.3157,
  },
  {
    id: validUuidForAddress[1],
    houseNumber: "45",
    street: "Thamel Marg",
    wardNumber: 16,
    municipality: "Kathmandu Metropolitan City",
    city: "Kathmandu",
    district: "Kathmandu",
    province: "Bagmati",
    latitude: 27.7154,
    longitude: 85.3123,
  },
  {
    id: validUuidForAddress[2],
    houseNumber: "8",
    street: "Lakeside Road",
    wardNumber: 6,
    municipality: "Pokhara Metropolitan City",
    city: "Pokhara",
    district: "Kaski",
    province: "Gandaki",
    latitude: 28.2096,
    longitude: 83.9556,
  },
  {
    id: validUuidForAddress[3],
    houseNumber: "23",
    street: "Mahendra Path",
    wardNumber: 3,
    municipality: "Pokhara Metropolitan City",
    city: "Pokhara",
    district: "Kaski",
    province: "Gandaki",
    latitude: 28.238,
    longitude: 83.9956,
  },
  {
    id: validUuidForAddress[4],
    houseNumber: "5",
    street: "Bhrikuti Mandap",
    wardNumber: 10,
    municipality: "Kathmandu Metropolitan City",
    city: "Kathmandu",
    district: "Kathmandu",
    province: "Bagmati",
    latitude: 27.6933,
    longitude: 85.3164,
  },
  {
    id: validUuidForAddress[5],
    houseNumber: "78",
    street: "Patan Dhoka",
    wardNumber: 5,
    municipality: "Lalitpur Metropolitan City",
    city: "Lalitpur",
    district: "Lalitpur",
    province: "Bagmati",
    latitude: 27.6644,
    longitude: 85.3188,
  },
  {
    id: validUuidForAddress[6],
    houseNumber: "3",
    street: "Boudha Road",
    wardNumber: 7,
    municipality: "Kathmandu Metropolitan City",
    city: "Kathmandu",
    district: "Kathmandu",
    province: "Bagmati",
    latitude: 27.7215,
    longitude: 85.3621,
  },
  {
    id: validUuidForAddress[7],
    houseNumber: "19",
    street: "Baneshwor Marg",
    wardNumber: 11,
    municipality: "Kathmandu Metropolitan City",
    city: "Kathmandu",
    district: "Kathmandu",
    province: "Bagmati",
    latitude: 27.6921,
    longitude: 85.3352,
  },
  {
    id: validUuidForAddress[8],
    houseNumber: "55",
    street: "Pulchowk Road",
    wardNumber: 2,
    municipality: "Lalitpur Metropolitan City",
    city: "Lalitpur",
    district: "Lalitpur",
    province: "Bagmati",
    latitude: 27.6762,
    longitude: 85.3176,
  },
  {
    id: validUuidForAddress[9],
    houseNumber: "101",
    street: "New Road",
    wardNumber: 23,
    municipality: "Kathmandu Metropolitan City",
    city: "Kathmandu",
    district: "Kathmandu",
    province: "Bagmati",
    latitude: 27.7041,
    longitude: 85.3131,
  },
];

const now = new Date();
const nextYear = new Date(now.getFullYear() + 1, now.getMonth(), now.getDate()).toISOString();
const twoYears = new Date(now.getFullYear() + 2, now.getMonth(), now.getDate()).toISOString();

async function seed() {
  console.log("Inserting addresses!");
  const insertedAddresses = await db.insert(address).values(addresses).returning();

  console.log("Inserting properties!");
  await db.insert(property).values([
    {
      id: validUuidForProperty[0],
      title: "Cozy House in Durbar Marg",
      slug: "cozy-house-durbar-marg",
      description: "A beautiful house near the heart of Kathmandu.",
      toRent: false,
      address: insertedAddresses[0].id,
      closeLandmark: "Narayanhiti Palace",
      propertyType: "House",
      availableFrom: now.toISOString(),
      availableTill: nextYear,
      price: 15000000,
      negotiable: true,
      status: "Sale",
      expiresOn: nextYear,
      views: 10,
      featured: true,
    },
    {
      id: validUuidForProperty[1],
      title: "Modern Apartment in Thamel",
      slug: "modern-apartment-thamel",
      description: "Stylish apartment in the tourist hub of Thamel.",
      toRent: true,
      address: insertedAddresses[1].id,
      closeLandmark: "Thamel Chowk",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 25000,
      negotiable: false,
      status: "Rent",
      expiresOn: nextYear,
      views: 34,
    },
    {
      id: validUuidForProperty[2],
      title: "Lakeside Villa Pokhara",
      slug: "lakeside-villa-pokhara",
      description: "Stunning villa with direct lake views in Pokhara.",
      toRent: false,
      address: insertedAddresses[2].id,
      closeLandmark: "Phewa Lake",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 25000000,
      negotiable: true,
      status: "Sale",
      expiresOn: twoYears,
      views: 52,
      featured: true,
    },
    {
      id: validUuidForProperty[3],
      title: "Land Plot on Mahendra Path",
      slug: "land-plot-mahendra-path",
      description: "Prime land plot available for commercial or residential use.",
      toRent: false,
      address: insertedAddresses[3].id,
      closeLandmark: "Pokhara Airport",
      propertyType: "Land",
      availableFrom: now.toISOString(),
      price: 8000000,
      negotiable: true,
      status: "Sale",
      expiresOn: twoYears,
      views: 18,
    },
    {
      id: validUuidForProperty[4],
      title: "Budget Room near Bhrikuti Mandap",
      slug: "budget-room-bhrikuti-mandap",
      description: "Affordable room for rent near exhibition ground.",
      toRent: true,
      address: insertedAddresses[4].id,
      closeLandmark: "Bhrikuti Mandap",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 8000,
      negotiable: false,
      status: "Rent",
      expiresOn: nextYear,
      views: 7,
    },
    {
      id: validUuidForProperty[5],
      title: "Heritage House in Patan",
      slug: "heritage-house-patan",
      description: "Traditional Newari style house near Patan Dhoka.",
      toRent: false,
      address: insertedAddresses[5].id,
      closeLandmark: "Patan Durbar Square",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 18000000,
      negotiable: true,
      status: "Sale",
      expiresOn: twoYears,
      views: 29,
      featured: true,
    },
    {
      id: validUuidForProperty[6],
      title: "Apartment near Boudhanath Stupa",
      slug: "apartment-boudhanath-stupa",
      description: "Peaceful apartment near the iconic Boudhanath Stupa.",
      toRent: true,
      address: insertedAddresses[6].id,
      closeLandmark: "Boudhanath Stupa",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 20000,
      negotiable: false,
      status: "Rent",
      expiresOn: nextYear,
      views: 41,
    },
    {
      id: validUuidForProperty[7],
      title: "Office Space in Baneshwor",
      slug: "office-space-baneshwor",
      description: "Ready to move commercial office space in Baneshwor.",
      toRent: true,
      address: insertedAddresses[7].id,
      closeLandmark: "Baneshwor Chowk",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 45000,
      negotiable: true,
      status: "Rent",
      expiresOn: nextYear,
      views: 63,
    },
    {
      id: validUuidForProperty[8],
      title: "Flat for Sale in Pulchowk",
      slug: "flat-sale-pulchowk",
      description: "Well maintained flat in the engineering hub of Pulchowk.",
      toRent: false,
      address: insertedAddresses[8].id,
      closeLandmark: "Pulchowk Campus",
      propertyType: "House",
      availableFrom: now.toISOString(),
      price: 12000000,
      negotiable: false,
      status: "Sale",
      expiresOn: twoYears,
      views: 22,
    },
    {
      id: validUuidForProperty[9],
      title: "Commercial Land on New Road",
      slug: "commercial-land-new-road",
      description: "Prime commercial land in the busiest street of Kathmandu.",
      toRent: false,
      address: insertedAddresses[9].id,
      closeLandmark: "Bishal Bazar",
      propertyType: "Land",
      availableFrom: now.toISOString(),
      price: 50000000,
      negotiable: true,
      status: "Sale",
      expiresOn: twoYears,
      views: 88,
      featured: true,
    },
  ]);

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seeding failed!", err);
  process.exit(1);
});
